---
# tasks file for backend

- name: Create Python backend app
  copy:
    dest: /tmp/app.py
    content: |
      from http.server import BaseHTTPRequestHandler, HTTPServer
      import json

      class SimpleHandler(BaseHTTPRequestHandler):
          def do_GET(self):
              self.send_response(200)
              self.send_header("Content-type", "application/json")
              self.end_headers()
              self.wfile.write(json.dumps({"message": "Hello from Backend!"}).encode())

      if __name__ == "__main__":
          server = HTTPServer(('', 8000), SimpleHandler)
          print("Server running on port 8000")
          server.serve_forever()

- name: Run backend Python HTTP server container
  docker_container:
    name: backend-api
    image: python:3.9-slim
    state: started
    restart_policy: always
    ports:
      - "8000:8000"
    volumes:
      - /tmp/app.py:/app.py:ro
    command: python /app.py

